GE Signa Parameters Fix #583
AnderBiguri/STIR pull request #1
Opened 2020-06-17 18:50 UTC by pwadhwa351

2020-06-18 17:28 UTC, pw351 commented
I am calculating DOI using inner radius (or physical radius of the scanner). The value is not present in header, what would you suggest?

Also  max_num_of_non_arc_corrected_bins is not really present in listmode file header (value is 0) but is present in the rdf file, I guess!

2020-06-18 17:29 UTC, pwadhwa351 commented
I am calculating DOI using inner radius (or physical radius of the scanner). The value is not present in header, what would you suggest?

Also max_num_of_non_arc_corrected_bins is not really present in listmode file header (value is 0) but is present in the rdf file, I guess!

2020-06-20 18:08 UTC, pwadhwa351 commented
@KrisThielemans I think this is done!

2020-06-20 18:55 UTC, KrisThielemans requested changes

2020-06-20 18:55 UTC, KrisThielemans commented on src/IO/GEHDF5Wrapper.cxx
> +    scanner_sptr->list_names(read_str_scanner);
```suggestion
```
`list_names()` returns the names. Here you have set it above.

2020-06-20 18:55 UTC, KrisThielemans commented on src/IO/GEHDF5Wrapper.cxx
> +    shared_ptr<Scanner> scanner_sptr(Scanner::get_scanner_from_name(read_str_scanner));
```suggestion
    shared_ptr<Scanner> scanner_sptr(Scanner::get_scanner_from_name(read_str_scanner));
    if (is_null_ptr(scanner_sptr))
       error("Scanner read from RDF file is " + read_str_scanner + ", but this is not supported yet");
    if (scanner_sptr->get_type() != Scanner::PETMR_Signa)
      warning("Scanner read from RDF file is " + read_str_scanner + ", but this code is only tested for the Signa PET/MR");
       
```

2020-06-20 18:55 UTC, KrisThielemans commented on src/IO/GEHDF5Wrapper.cxx
> +    {
```suggestion
```
let's always read it. checks are below

2020-06-20 18:55 UTC, KrisThielemans commented on src/IO/GEHDF5Wrapper.cxx
> +    }
```suggestion
```
removed, as `if` above removed

2020-06-20 20:27 UTC, KrisThielemans approved these changes

2020-06-20 20:30 UTC, KrisThielemans commented
Thanks @pwadhwa351 !

@AnderBiguri could you merge this? I cannot.

2020-06-20 20:31 UTC, merged

2020-06-20 20:40 UTC, pwadhwa351 commented
Ah! Thanks for the merge, one last thing was left! Basically we need to add #include "stir/is_null_ptr.h" in GEHDF5Wrapper.cxx!

2020-06-20 22:01 UTC, KrisThielemans commented
done!

Could you share the uncompressed sino with me as well? I don't think I have it.